### ISSUE TITLE
Add sidebar icon

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/ide-ext-vscode#10]
Add a sidebar Icon w/ the TC logo that brings up a tab that 
- describes all the capabilities of the extension
- describes how to get started (ie: setting login credentials)
- has shortcuts to the commands in the command palette  
- any other goodness

**Comment by cwdcwd** [comment]
![image](https://user-images.githubusercontent.com/1504607/62571888-7c1a9980-b860-11e9-999c-4dc050f2a4d4.png)
this side bar

**Comment by callmekatootie** [comment]
@cwdcwd Do we have an icon that we can use (or could a design provider one)? The specification for the icon can be [found here](https://code.visualstudio.com/api/references/contribution-points#Icon-specifications)

**Comment by cwdcwd** [comment]
I'll get that whipped up.

**Comment by cwdcwd** [comment]
[Logo Archive.zip](https://github.com/topcoder-platform/ide-ext-vscode/files/3486601/Logo.Archive.zip)
@callmekatootie ☝️

**Comment by callmekatootie** [comment]
@cwdcwd 

[Reference](https://code.visualstudio.com/api/references/contribution-points#contributes.viewsContainers)

In the sidebar, we essentially can only provide a Tree based view - and the user has to click on the tree nodes to get further details in the main area.

So I am thinking the tree structure would be something as follows:

```
Your Active Contests
├── Topcoder-X - August 2019 release challenge
├── Topcoder Connect - Form Editor
├── Topbot - Upgrade the version of botkit
├── Hoherberg Ski School Priority Bug Fixes Part 6 Code Challenge

Your Active Submissions
├── Data Request Ideation (Phase II)- Power World
├── Cycle Time - REST API Dev

Topcoder
├── Extension Features
├── Getting Started
├── Active Challenges
```

**Question 1: Is the above tree structure fine?**

What you stated, namely `has shortcuts to the commands in the command palette` - we can only provide "View Active Challenges" - the other commands don't have a view and thus cannot be displayed here. **Question 2 - Is this ok?**

Now, in order to display the list of contest I have registered under (or have a role to play), I looked at the Topcoder Dashboard and came across the following API: https://api.topcoder.com/v4/members/callmekatootie/challenges/?filter=status%3DACTIVE&limit=50&offset=0 which I suppose returns the list of contests that I have a role to play (any role and not just submitter). I suppose that works for "Your Active Contests" category and I can use the user's jwt token to get the details - **Question 3 - Did I get the API right? Is it ok to make use of it in this context?**

As for displaying contests where I have active submissions - not sure which API I would need to display that information... **Question 4: Let me know if you have these details. Definitely not a blocker**

The nodes under Topcoder are Static (last one is the same view as the current view all challenges) so don't need any information here.

Let me know your thoughts on the questions above

**Comment by cwdcwd** [comment]
1. looks great!
2. I think it's ok. we'll evolve this as we go
3. It's fine for v3/v4. v5 we'll do this differently 
4. I think active subs is any challenge I'm on that is still open, right?

**Comment by callmekatootie** [comment]
Point 4: No, It would be the contests that you registered for, that is still open (but not in submission phase) AND for which I have uploaded submissions - so that the user can see the status of their submission (their scores, reviews etc) - at least, that's what I have in mind. What you are talking about is already covered under Point 3.

**Comment by callmekatootie** [comment]
For points 1, 2 and 3, Contest launched: http://www.topcoder.com/challenge-details/30099778/?type=develop

**Comment by callmekatootie** [comment]
I guess we can take up discussion for Point 4 under #14 instead of in this ticket

**Comment by callmekatootie** [comment]
This has now been carried out.
