### ISSUE TITLE
changelog not updated

### ISSUE THREAD

**Issue by veshu** [topcoder-platform/ide-ext-vscode#55]
Though there is new version the change log of the extension is not updated.

**Comment by callmekatootie** [comment]
Thank you for reporting this. I forgot that we have a dedicated CHANGELOG.md file.

I might look at removing it altogether because I have been maintaining an active change log in the releases section: https://github.com/topcoder-platform/ide-ext-vscode/releases - @veshu let me know if this helps

Would not make sense to maintain it in two places...

Need to first check if a change log file is mandatory for publishing extension... not sure why I added that file in the first place...

**Comment by veshu** [comment]
It is not mandatory, but keeping it is best practices as extension gets updated automatically and when I want to see the changes I could see what new version brings without having to go to the repo.

Mostly every extension has this maintained.

**Comment by callmekatootie** [comment]
The Changelog is now kept in sync. Kindly pull the latest release to get the changes.
